-- ALTER SEQUENCE seminar_type_id_seq 	OWNED BY seminar_type.id;
-- ALTER SEQUENCE method_type_id_seq 	OWNED BY method_type.id;
-- ALTER SEQUENCE method_level_id_seq 	OWNED BY method_level.id;
-- ALTER SEQUENCE method_id_seq 		OWNED BY method.id;
-- ALTER SEQUENCE attachment_id_seq	OWNED BY attachment.id;
-- ALTER SEQUENCE mdb_user_id_seq		OWNED BY mdb_user.id;